# -*- coding: utf-8 -*-
"""clean_functions.ipynb

Automatically generated by Colaboratory.

"""

# Import Libraries
import pandas as pd


def clean_immigration_spark_df(df):
    """
        Clean immigration dataframe
    """
    
    # remove columns missing most values
    columns = ['insnum', 'entdepu', 'occup']
    df = df.drop(*columns)
    
    return df


def clean_temperature_spark_df(df):
    """
        Clean temperature dataframe
    """
    
    # drop rows with N/A in subset column
    df = df.dropna(subset=['AverageTemperature'])
    
    # drop duplicate rows
    df = df.drop_duplicates(subset=['dt', 'City', 'Country'])
    
    return df

def group_temperature_data(df):
    """
        Group temperature data
    """
    
    temp_df = df.select(['Country', 'AverageTemperature']).groupby('Country').avg()
    
    group_df = temp_df.withColumnRenamed('avg(AverageTemperature)', 'average_temperature')
    
    return group_df


def clean_demographics_spark_df(df):
    """
        Clean demographics dataframe
    """
    
    # drop rows with N/A
    temp_df = df.dropna(subset=[
                                'Male Population',
                                'Female Population',
                                'Number of Veterans',
                                'Foreign-born',
                                'Average Household Size'
                              ]
                        )
    
    # drop duplicates
    final_df = temp_df.dropDuplicates(subset=['City', 'State', 'State Code', 'Race'])
    
    return final_df

